1/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
  	resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

1/app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

1/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

1/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "abroom", password: "secret", except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new()
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title,:text)
		end
end

1/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "abroom", password: "secret", only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter,:body)
		end
end

1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

1/app/helpers/application_helper.rb
module ApplicationHelper
end

1/app/helpers/articles_helper.rb
module ArticlesHelper
end

1/app/helpers/comments_helper.rb
module CommentsHelper
end

1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

1/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count,"error") %>
				prohibited this article from being saved.
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |error| %>
					<li><%= error %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_field :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

1/app/views/articles/edit.html.erb
<h1>Editing a FUCKING Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

1/app/views/articles/index.html.erb
<h1>Listing all the flipping articles we got</h1>

<%= link_to 'New Article', new_article_path %>

<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
	</tr>
	<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.text %></td>
			<td><%= link_to 'Show', article_path(article) %></td>
			<td><%= link_to 'Edit', edit_article_path(article) %></td>
			<td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
</table>

1/app/views/articles/new.html.erb
<h1>New FUCKING Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

1/app/views/articles/show.html.erb
<h1>showing your FUCKING Article</h1>
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

<h2>Listing all Fucking comments for this particular article</h2>
<%= render @article.comments %>

<h2>Add a FUCKING comment</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path %>
<%= link_to 'Back', articles_path %>

1/app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

1/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

1/app/views/welcome/index.html.erb
<h1>Ruby Blog Tutorial!</h1>
<%= link_to 'My Blog', controller: 'articles' %>